# Generated by Django 4.2.17 on 2024-12-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocoloData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('form_id', models.CharField(blank=True, max_length=50, null=True)),
                ('procedimiento_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cirujano_1', models.CharField(blank=True, max_length=100, null=True)),
                ('instrumentista', models.CharField(blank=True, max_length=100, null=True)),
                ('cirujano_2', models.CharField(blank=True, max_length=100, null=True)),
                ('circulante', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_ayudante', models.CharField(blank=True, max_length=100, null=True)),
                ('anestesiologo', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_ayudante', models.CharField(blank=True, max_length=100, null=True)),
                ('ayudante_anestesia', models.CharField(blank=True, max_length=100, null=True)),
                ('tercer_ayudante', models.CharField(blank=True, max_length=100, null=True)),
                ('otros', models.CharField(blank=True, max_length=255, null=True)),
                ('membrete', models.TextField(blank=True, null=True)),
                ('dieresis', models.TextField(blank=True, null=True)),
                ('exposicion', models.TextField(blank=True, null=True)),
                ('hallazgo', models.TextField(blank=True, null=True)),
                ('operatorio', models.TextField(blank=True, null=True)),
                ('complicaciones_operatorio', models.TextField(blank=True, null=True)),
                ('datos_cirugia', models.TextField(blank=True, null=True)),
                ('procedimientos', models.JSONField(blank=True, null=True)),
                ('lateralidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('tipo_anestesia', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosticos', models.JSONField(blank=True, null=True)),
                ('printed', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('insumos', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
