# Generated by Django 4.2.17 on 2024-12-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hc_number', models.CharField(max_length=255)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('lname', models.CharField(blank=True, max_length=100)),
                ('lname2', models.CharField(blank=True, max_length=100, null=True)),
                ('fname', models.CharField(blank=True, max_length=100)),
                ('mname', models.CharField(blank=True, max_length=100, null=True)),
                ('afiliacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                ('lugar_trabajo', models.CharField(blank=True, max_length=255, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=255, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=255, null=True)),
                ('id_procedencia', models.CharField(blank=True, max_length=255, null=True)),
                ('id_referido', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'patient_data',
            },
        ),
    ]
