# Generated by Django 4.2.17 on 2024-12-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [

    ]
