# Generated by Django 4.2.17 on 2025-01-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoProyectado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('form_id', models.CharField(max_length=255)),
                ('procedimiento_proyectado', models.TextField()),
                ('doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('hc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='pacientes.patientdata')),
            ],
            options={
                'verbose_name': 'Procedimiento Proyectado',
                'verbose_name_plural': 'Procedimientos Proyectados',
                'db_table': 'procedimiento_proyectado',
            },
        ),
    ]
