# Generated by Django 4.2.17 on 2024-12-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedimientoProyectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('procedimiento_proyectado', models.TextField()),
                ('doctor', models.CharField(blank=True, max_length=255, null=True)),
                ('hc_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudProcedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_number', models.CharField(max_length=20)),
                ('form_id', models.CharField(max_length=20)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('afiliacion', models.CharField(blank=True, max_length=100, null=True)),
                ('procedimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('ojo', models.CharField(blank=True, max_length=10, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=10, null=True)),
                ('producto', models.CharField(blank=True, max_length=255, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('secuencia', models.IntegerField()),
            ],
        ),
    ]
