# Generated by Django 4.2.17 on 2024-12-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_number', models.CharField(blank=True, max_length=50, null=True)),
                ('form_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('enfermedad_actual', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosticos', models.JSONField(blank=True, null=True)),
                ('examenes', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
