# Generated by Django 4.2.17 on 2025-01-08 18:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_procedimientoproyectado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField()),
                ('enfermedad_actual', models.TextField(blank=True, null=True)),
                ('examen_fisico', models.TextField(blank=True, null=True)),
                ('plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosticos', models.JSONField(blank=True, null=True)),
                ('examenes', models.JSONField(blank=True, null=True)),
                ('hc_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.patientdata')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta_data',
            },
        ),
    ]
