# Generated by Django 4.2.17 on 2024-12-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cirugia', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=50)),
                ('membrete', models.TextField()),
                ('medicacion', models.IntegerField(blank=True, null=True)),
                ('cardex', models.IntegerField(blank=True, null=True)),
                ('dieresis', models.TextField(blank=True, null=True)),
                ('exposicion', models.TextField(blank=True, null=True)),
                ('hallazgo', models.TextField(blank=True, null=True)),
                ('operatorio', models.TextField(blank=True, null=True)),
                ('anestesia', models.CharField(default='REGIONAL', max_length=55)),
                ('complicacionesoperatorio', models.CharField(blank=True, max_length=10, null=True)),
                ('perdidasanguineat', models.CharField(blank=True, max_length=10, null=True)),
                ('staffCount', models.IntegerField(blank=True, null=True)),
                ('codigoCount', models.IntegerField(blank=True, null=True)),
                ('diagnosticoCount', models.IntegerField(blank=True, null=True)),
                ('horas', models.CharField(blank=True, max_length=3, null=True)),
                ('dx_pre', models.TextField()),
                ('dx_post', models.TextField()),
                ('imagen_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'procedimientos',
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion', models.CharField(max_length=50)),
                ('trabajador', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('selector', models.CharField(max_length=255)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicos', to='plantillas.procedimiento')),
            ],
            options={
                'verbose_name': 'Procedimiento Técnico',
                'verbose_name_plural': 'Procedimientos Técnicos',
                'db_table': 'procedimientos_tecnicos',
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoDiagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('definitivo', models.CharField(max_length=255)),
                ('lateralidad', models.CharField(max_length=255)),
                ('selector', models.CharField(max_length=255)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='plantillas.procedimiento')),
            ],
            options={
                'verbose_name': 'Procedimiento Diagnóstico',
                'verbose_name_plural': 'Procedimientos Diagnósticos',
                'db_table': 'procedimientos_diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='ProcedimientoCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lateralidad', models.CharField(max_length=255)),
                ('selector', models.CharField(max_length=255)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='plantillas.procedimiento')),
            ],
            options={
                'verbose_name': 'Procedimiento Código',
                'verbose_name_plural': 'Procedimientos Códigos',
                'db_table': 'procedimientos_codigos',
            },
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kardex', to='plantillas.procedimiento')),
            ],
            options={
                'verbose_name': 'Kadex',
                'verbose_name_plural': 'Kardex',
                'db_table': 'kardex',
            },
        ),
        migrations.CreateModel(
            name='InsumosPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insumos', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='plantillas.procedimiento')),
            ],
            options={
                'verbose_name': 'Insumos Packs',
                'verbose_name_plural': 'Insumos Pack',
                'db_table': 'insumos_pack',
            },
        ),
        migrations.CreateModel(
            name='Evolucion005',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_evolucion', models.TextField(blank=True, null=True)),
                ('pre_indicacion', models.TextField(blank=True, null=True)),
                ('post_evolucion', models.TextField(blank=True, null=True)),
                ('post_indicacion', models.TextField(blank=True, null=True)),
                ('alta_evolucion', models.TextField(blank=True, null=True)),
                ('alta_indicacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('procedimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='plantillas.procedimiento')),
            ],
            options={
                'verbose_name': 'Evolución 005',
                'verbose_name_plural': 'Evoluciones 005',
                'db_table': 'evolucion005',
            },
        ),
    ]
