# Generated by Django 4.2.17 on 2024-12-28 00:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import plantillas.models


class Migration(migrations.Migration):

    dependencies = [
        ('plantillas', '0002_alter_procedimiento_imagen_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumospack',
            options={'verbose_name': 'Insumos Pack', 'verbose_name_plural': 'Insumos Pack'},
        ),
        migrations.AlterModelOptions(
            name='kardex',
            options={'verbose_name': 'Kardex', 'verbose_name_plural': 'Kardex'},
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procedimientotecnico',
            name='lateralidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='categoria',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='imagen_link',
            field=models.ImageField(blank=True, null=True, upload_to=plantillas.models.procedimiento_image_path),
        ),
        migrations.AlterField(
            model_name='procedimientocodigo',
            name='lateralidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimientocodigo',
            name='procedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='plantillas.procedimiento'),
        ),
        migrations.AlterField(
            model_name='procedimientocodigo',
            name='selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimientodiagnostico',
            name='lateralidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimientodiagnostico',
            name='procedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='plantillas.procedimiento'),
        ),
        migrations.AlterField(
            model_name='procedimientodiagnostico',
            name='selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='procedimientotecnico',
            name='procedimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='plantillas.procedimiento'),
        ),
        migrations.AlterField(
            model_name='procedimientotecnico',
            name='selector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='procedimiento',
            index=models.Index(fields=['categoria'], name='idx_categoria'),
        ),
        migrations.AddIndex(
            model_name='procedimiento',
            index=models.Index(fields=['id'], name='idx_procedimiento_id'),
        ),
    ]
