# Generated by Django 4.2.17 on 2024-12-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'verbose_name': 'insumo', 'verbose_name_plural': 'insumos'},
        ),
        migrations.AlterModelOptions(
            name='medicamento',
            options={'verbose_name': 'medicamento', 'verbose_name_plural': 'medicamentos'},
        ),
        migrations.AlterModelTable(
            name='insumo',
            table='insumos',
        ),
        migrations.AlterModelTable(
            name='medicamento',
            table='medicamentos',
        ),
    ]
