# Generated by Django 4.2.17 on 2024-12-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='firma',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
    ]
